export const enum SteamCMDStatus {
    INITIALIZE = "INITIALIZE",
    STEAMCMDSETUP = "STEAMCMD SETUP",
    CSGODOWNLOAD = "CSGO DOWNLOAD",
    STEAMCMD_FINISHED = "STEAMCMD FINISHED",
    CSGO_FINISHED = "CSGO FINISHED",
    CANCELLED = "CANCELED",
    ERROR = "ERROR"
}

export const enum IPCSteamCMDCommands {
    RUN_STEAMCMD_DOWNLOAD = "RUN_STEAMCMD_DOWNLOAD",
    RUN_CSGO_DOWNLOAD = "RUN_CSGO_DOWNLOAD",
    STEAMCMD_STATUS_UPDATE = "STEAMCMD_STATUS_UPDATE",
    STEAMCMD_MESSAGE_UPDATE = "STEAMCMD_MESSAGE_UPDATE",
    CSGO_STEAMCMD_MESSAGE_UPDATE = "CSGO_STEAMCMD_MESSAGE_UPDATE"
}

export const enum IPCSteamModInstallerCommands {
    RUN_MODINSTALLER_SETUP = "RUN_MODINSTALLER_DOWNLOAD",
    MODINSTALLER_MESSAGE_UPDATE = "MODINSTALLER_MESSAGE_UPDATE",
    MODINSTALLER_STATUS_UPDATE = "MODINSTALLER_STATUS_UPDATE",
}

export const enum ModInstallerStatus {
    MODSINSTALLING = "MODS INSTALALLING",
    MODSENABLING = "MODS ENABLING",
    FINISHED = "FINISHED",
    ERROR = "ERROR"
}

export const enum ServerStatus {
    NOT_READY = "NOT_READY",
    READY = "READY",
    RUNNING = "RUNNING",
    CONNECTED = "CONNECTED"
}

export const enum IPCCommunicationCommands {
    REQUEST_SERVER_STATUSES = "REQUEST_SERVER_STATUSES",
}